# Generated by Django 4.2.4 on 2023-08-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_actor_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ('name',), 'verbose_name': 'Ator', 'verbose_name_plural': 'Atores'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('name',), 'verbose_name': 'Filme', 'verbose_name_plural': 'Filmes'},
        ),
        migrations.AddField(
            model_name='actor',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
