# Generated by Django 4.2.4 on 2023-08-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0005_rename_create_date_actor_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
